export const CLEAR_POSTS = 'CLEAR_POSTS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_MORE_POSTS = 'FETCH_MORE_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

// DUMMMY DATA
export const FETCH_POSTS_DUMMY_DATA = 'FETCH_POSTS_DUMMY_DATA';
export const FETCH_MORE_POSTS_DUMMY_DATA = 'FETCH_MORE_POSTS_DUMMY_DATA';
export const FETCH_POST_DUMMY_DATA = 'FETCH_POST_DUMMY_DATA';
export const CREATE_POST_DUMMY_DATA = 'CREATE_POST_DUMMY_DATA';
export const UPDATE_POST_DUMMY_DATA = 'UPDATE_POST_DUMMY_DATA';
export const DELETE_POST_DUMMY_DATA = 'DELETE_POST_DUMMY_DATA';